#!/bin/bash

REL=`lsb_release`

if [ $? -eq 0 ]; then

    WRKDIR=`readlink -f $(pwd)`
    docker logs -f $(docker run -d -u="developer" --name epgsql_pool -v $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK -v $(pwd)/../:/workspace/base  epgsql_pool $1) | sed "s#\/workspace\/base#${WRKDIR}#"

else

    boot2docker ssh -A -t "docker run --rm=true -t -i --name epgsql_pool -v \$(dirname \${SSH_AUTH_SOCK}):\$(dirname \${SSH_AUTH_SOCK}) -e SSH_AUTH_SOCK=\${SSH_AUTH_SOCK} -v $(pwd)/../:/workspace/base  epgsql_pool $1"

fi

docker rm -f epgsql_pool

