#!/bin/bash

echo "I smack you janky!"

. /home/ubuntu/erlang/R16B03-1/activate

pushd ..
rm -rf epgsql
git clone git@github.com:miranetworks/epgsql
cd epgsql
make
popd


su postgres -c "cat sql/create_db.sql | psql"

make test


#EOF
